/**
 * aiToolsCatalog.js
 * ---------------------------------------------------------------------------
 * Hand-curated catalog of 100 AI tools for the "AI Tools Directory".
 *
 * Each entry is a *sparse* tool object: descriptions, shortDesc and
 * claudeTake are filled at seed time by Gemini (see aiToolsEnrich.js).
 *
 * Composition:
 *   - 20 official Claude skills/features (type: 'claude-skill')
 *   - 25 MCP connectors                  (type: 'mcp-connector')
 *   - 30 trending AI GitHub repos        (type: 'github-repo')
 *   - 25 LLM / AI products               (type: 'llm-product')
 */

const CATALOG = [
  // ─── 20 Claude skills / features ──────────────────────────────────────────
  {
    slug: 'claude-code',
    name: 'Claude Code',
    type: 'claude-skill',
    category: 'coding',
    homepage: 'https://claude.com/product/claude-code',
    repoUrl: null,
    installCommand: 'npm install -g @anthropic-ai/claude-code',
    pricing: 'paid',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['agentic', 'cli', 'coding', 'anthropic'],
  },
  {
    slug: 'claude-code-plugins',
    name: 'Claude Code Plugins',
    type: 'claude-skill',
    category: 'coding',
    homepage: 'https://docs.anthropic.com/en/docs/claude-code/plugins',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['plugins', 'extensibility', 'anthropic'],
  },
  {
    slug: 'claude-skills-office',
    name: 'Claude Skills (PPTX/DOCX/XLSX/PDF)',
    type: 'claude-skill',
    category: 'productivity',
    homepage: 'https://docs.anthropic.com/en/docs/agents/skills',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'solo-founders'],
    tags: ['office', 'documents', 'skills'],
  },
  {
    slug: 'claude-computer-use',
    name: 'Computer Use',
    type: 'claude-skill',
    category: 'agents',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/computer-use',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['coding-agents', 'researchers'],
    tags: ['agents', 'automation', 'computer-use'],
  },
  {
    slug: 'claude-citations',
    name: 'Citations',
    type: 'claude-skill',
    category: 'research',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/citations',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['researchers', 'content-writers'],
    tags: ['rag', 'sources', 'grounding'],
  },
  {
    slug: 'claude-prompt-caching',
    name: 'Prompt Caching',
    type: 'claude-skill',
    category: 'coding',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'coding-agents'],
    tags: ['performance', 'cost', 'api'],
  },
  {
    slug: 'claude-files-api',
    name: 'Files API',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/files',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'coding-agents'],
    tags: ['files', 'api', 'documents'],
  },
  {
    slug: 'claude-batch-api',
    name: 'Batch API',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/batch-processing',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'data-analysts'],
    tags: ['batch', 'api', 'cost-optimization'],
  },
  {
    slug: 'claude-agent-sdk',
    name: 'Claude Agent SDK',
    type: 'claude-skill',
    category: 'agents',
    homepage: 'https://docs.anthropic.com/en/docs/agents/agent-sdk',
    repoUrl: 'https://github.com/anthropics/claude-agent-sdk-python',
    installCommand: 'pip install claude-agent-sdk',
    pricing: 'free',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['agents', 'sdk', 'python'],
  },
  {
    slug: 'claude-in-chrome',
    name: 'Claude in Chrome',
    type: 'claude-skill',
    category: 'productivity',
    homepage: 'https://www.anthropic.com/news/claude-for-chrome',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['solo-founders', 'researchers'],
    tags: ['browser', 'extension', 'agents'],
  },
  {
    slug: 'claude-for-slack',
    name: 'Claude for Slack',
    type: 'claude-skill',
    category: 'productivity',
    homepage: 'https://www.anthropic.com/claude-for-slack',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'solo-founders'],
    tags: ['slack', 'collaboration', 'integration'],
  },
  {
    slug: 'claude-for-sheets',
    name: 'Claude for Google Sheets',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://workspace.google.com/marketplace/app/claude_for_sheets/909417792257',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['data-analysts', 'marketers'],
    tags: ['sheets', 'spreadsheet', 'gsuite'],
  },
  {
    slug: 'claude-projects',
    name: 'Claude Projects',
    type: 'claude-skill',
    category: 'productivity',
    homepage: 'https://www.anthropic.com/news/projects',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['solo-founders', 'content-writers'],
    tags: ['projects', 'context', 'organization'],
  },
  {
    slug: 'claude-artifacts',
    name: 'Claude Artifacts',
    type: 'claude-skill',
    category: 'coding',
    homepage: 'https://www.anthropic.com/news/artifacts',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['coding-agents', 'designers'],
    tags: ['artifacts', 'prototyping', 'preview'],
  },
  {
    slug: 'claude-vision',
    name: 'Claude Vision',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/vision',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['designers', 'data-analysts'],
    tags: ['vision', 'multimodal', 'images'],
  },
  {
    slug: 'claude-tool-use',
    name: 'Tool Use',
    type: 'claude-skill',
    category: 'agents',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['function-calling', 'tools', 'agents'],
  },
  {
    slug: 'claude-extended-thinking',
    name: 'Extended Thinking',
    type: 'claude-skill',
    category: 'research',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['researchers', 'coding-agents'],
    tags: ['reasoning', 'thinking', 'depth'],
  },
  {
    slug: 'claude-message-batches',
    name: 'Message Batches',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://docs.anthropic.com/en/api/creating-message-batches',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['enterprise', 'data-analysts'],
    tags: ['batch', 'bulk', 'cost'],
  },
  {
    slug: 'claude-pdf-support',
    name: 'PDF Support',
    type: 'claude-skill',
    category: 'data',
    homepage: 'https://docs.anthropic.com/en/docs/build-with-claude/pdf-support',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['researchers', 'enterprise'],
    tags: ['pdf', 'documents', 'multimodal'],
  },
  {
    slug: 'claude-mcp',
    name: 'Model Context Protocol',
    type: 'claude-skill',
    category: 'agents',
    homepage: 'https://modelcontextprotocol.io',
    repoUrl: 'https://github.com/modelcontextprotocol',
    installCommand: null,
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['mcp', 'protocol', 'integration'],
  },

  // ─── 25 MCP connectors ────────────────────────────────────────────────────
  {
    slug: 'mcp-slack',
    name: 'Slack MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add slack npx -y @modelcontextprotocol/server-slack',
    pricing: 'open-source',
    bestFor: ['enterprise', 'solo-founders'],
    tags: ['slack', 'chat', 'mcp'],
  },
  {
    slug: 'mcp-github',
    name: 'GitHub MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://github.com/github/github-mcp-server',
    repoUrl: 'https://github.com/github/github-mcp-server',
    installCommand: 'claude mcp add github npx -y @modelcontextprotocol/server-github',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['github', 'git', 'mcp'],
  },
  {
    slug: 'mcp-linear',
    name: 'Linear MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://linear.app/changelog/2025-05-01-mcp',
    repoUrl: null,
    installCommand: 'claude mcp add linear https://mcp.linear.app/sse',
    pricing: 'freemium',
    bestFor: ['enterprise', 'coding-agents'],
    tags: ['linear', 'issues', 'mcp'],
  },
  {
    slug: 'mcp-notion',
    name: 'Notion MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://developers.notion.com/docs/mcp',
    repoUrl: 'https://github.com/makenotion/notion-mcp-server',
    installCommand: 'claude mcp add notion npx -y @notionhq/notion-mcp-server',
    pricing: 'freemium',
    bestFor: ['content-writers', 'researchers'],
    tags: ['notion', 'docs', 'mcp'],
  },
  {
    slug: 'mcp-sentry',
    name: 'Sentry MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://docs.sentry.io/product/sentry-mcp/',
    repoUrl: 'https://github.com/getsentry/sentry-mcp',
    installCommand: 'claude mcp add sentry npx -y @sentry/mcp-server',
    pricing: 'freemium',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['sentry', 'errors', 'observability'],
  },
  {
    slug: 'mcp-postgres',
    name: 'PostgreSQL MCP',
    type: 'mcp-connector',
    category: 'data',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add postgres npx -y @modelcontextprotocol/server-postgres',
    pricing: 'open-source',
    bestFor: ['data-analysts', 'coding-agents'],
    tags: ['postgres', 'sql', 'database'],
  },
  {
    slug: 'mcp-filesystem',
    name: 'Filesystem MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add filesystem npx -y @modelcontextprotocol/server-filesystem',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['files', 'local', 'mcp'],
  },
  {
    slug: 'mcp-playwright',
    name: 'Playwright MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://github.com/microsoft/playwright-mcp',
    repoUrl: 'https://github.com/microsoft/playwright-mcp',
    installCommand: 'claude mcp add playwright npx -y @playwright/mcp',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['playwright', 'browser', 'testing'],
  },
  {
    slug: 'mcp-puppeteer',
    name: 'Puppeteer MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add puppeteer npx -y @modelcontextprotocol/server-puppeteer',
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['puppeteer', 'browser', 'automation'],
  },
  {
    slug: 'mcp-memory',
    name: 'Memory MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add memory npx -y @modelcontextprotocol/server-memory',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'researchers'],
    tags: ['memory', 'knowledge-graph', 'mcp'],
  },
  {
    slug: 'mcp-brave-search',
    name: 'Brave Search MCP',
    type: 'mcp-connector',
    category: 'research',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add brave npx -y @modelcontextprotocol/server-brave-search',
    pricing: 'freemium',
    bestFor: ['researchers'],
    tags: ['search', 'brave', 'web'],
  },
  {
    slug: 'mcp-gdrive',
    name: 'Google Drive MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add gdrive npx -y @modelcontextprotocol/server-gdrive',
    pricing: 'freemium',
    bestFor: ['enterprise', 'content-writers'],
    tags: ['drive', 'google', 'docs'],
  },
  {
    slug: 'mcp-stripe',
    name: 'Stripe MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://docs.stripe.com/building-with-llms#mcp',
    repoUrl: 'https://github.com/stripe/agent-toolkit',
    installCommand: 'claude mcp add stripe npx -y @stripe/mcp',
    pricing: 'paid',
    bestFor: ['solo-founders', 'enterprise'],
    tags: ['stripe', 'payments', 'finance'],
  },
  {
    slug: 'mcp-cloudflare',
    name: 'Cloudflare MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://github.com/cloudflare/mcp-server-cloudflare',
    repoUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    installCommand: 'claude mcp add cloudflare npx -y @cloudflare/mcp-server-cloudflare',
    pricing: 'freemium',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['cloudflare', 'workers', 'edge'],
  },
  {
    slug: 'mcp-supabase',
    name: 'Supabase MCP',
    type: 'mcp-connector',
    category: 'data',
    homepage: 'https://supabase.com/docs/guides/getting-started/mcp',
    repoUrl: 'https://github.com/supabase-community/supabase-mcp',
    installCommand: 'claude mcp add supabase npx -y @supabase/mcp-server-supabase',
    pricing: 'freemium',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['supabase', 'database', 'backend'],
  },
  {
    slug: 'mcp-figma',
    name: 'Figma MCP',
    type: 'mcp-connector',
    category: 'design',
    homepage: 'https://www.figma.com/blog/introducing-figmas-dev-mode-mcp-server/',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['designers', 'coding-agents'],
    tags: ['figma', 'design', 'mcp'],
  },
  {
    slug: 'mcp-atlassian',
    name: 'Atlassian MCP (Jira/Confluence)',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://www.atlassian.com/platform/remote-mcp-server',
    repoUrl: null,
    installCommand: 'claude mcp add atlassian https://mcp.atlassian.com/v1/sse',
    pricing: 'freemium',
    bestFor: ['enterprise'],
    tags: ['jira', 'confluence', 'atlassian'],
  },
  {
    slug: 'mcp-sqlite',
    name: 'SQLite MCP',
    type: 'mcp-connector',
    category: 'data',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add sqlite npx -y @modelcontextprotocol/server-sqlite',
    pricing: 'open-source',
    bestFor: ['data-analysts', 'coding-agents'],
    tags: ['sqlite', 'database', 'mcp'],
  },
  {
    slug: 'mcp-fetch',
    name: 'Fetch MCP',
    type: 'mcp-connector',
    category: 'research',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add fetch npx -y @modelcontextprotocol/server-fetch',
    pricing: 'open-source',
    bestFor: ['researchers', 'coding-agents'],
    tags: ['fetch', 'http', 'web'],
  },
  {
    slug: 'mcp-git',
    name: 'Git MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add git npx -y @modelcontextprotocol/server-git',
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['git', 'vcs', 'mcp'],
  },
  {
    slug: 'mcp-sequential-thinking',
    name: 'Sequential Thinking MCP',
    type: 'mcp-connector',
    category: 'research',
    homepage: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    repoUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'claude mcp add sequential-thinking npx -y @modelcontextprotocol/server-sequential-thinking',
    pricing: 'open-source',
    bestFor: ['researchers', 'coding-agents'],
    tags: ['reasoning', 'thinking', 'mcp'],
  },
  {
    slug: 'mcp-vercel',
    name: 'Vercel MCP',
    type: 'mcp-connector',
    category: 'coding',
    homepage: 'https://vercel.com/changelog/mcp-server',
    repoUrl: null,
    installCommand: 'claude mcp add vercel https://mcp.vercel.com/sse',
    pricing: 'freemium',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['vercel', 'deploy', 'mcp'],
  },
  {
    slug: 'mcp-sentry-issues',
    name: 'Asana MCP',
    type: 'mcp-connector',
    category: 'productivity',
    homepage: 'https://developers.asana.com/docs/mcp-server',
    repoUrl: null,
    installCommand: 'claude mcp add asana https://mcp.asana.com/sse',
    pricing: 'freemium',
    bestFor: ['enterprise'],
    tags: ['asana', 'projects', 'mcp'],
  },
  {
    slug: 'mcp-hubspot',
    name: 'HubSpot MCP',
    type: 'mcp-connector',
    category: 'marketing',
    homepage: 'https://developers.hubspot.com/mcp',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['marketers', 'enterprise'],
    tags: ['hubspot', 'crm', 'marketing'],
  },
  {
    slug: 'mcp-perplexity',
    name: 'Perplexity MCP',
    type: 'mcp-connector',
    category: 'research',
    homepage: 'https://github.com/ppl-ai/modelcontextprotocol',
    repoUrl: 'https://github.com/ppl-ai/modelcontextprotocol',
    installCommand: 'claude mcp add perplexity npx -y server-perplexity-ask',
    pricing: 'paid',
    bestFor: ['researchers', 'content-writers'],
    tags: ['perplexity', 'search', 'research'],
  },

  // ─── 30 trending AI GitHub repos ──────────────────────────────────────────
  {
    slug: 'langchain',
    name: 'LangChain',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://www.langchain.com',
    repoUrl: 'https://github.com/langchain-ai/langchain',
    installCommand: 'pip install langchain',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['llm', 'framework', 'python'],
  },
  {
    slug: 'autogen',
    name: 'AutoGen',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://microsoft.github.io/autogen/',
    repoUrl: 'https://github.com/microsoft/autogen',
    installCommand: 'pip install pyautogen',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'researchers'],
    tags: ['multi-agent', 'microsoft', 'framework'],
  },
  {
    slug: 'crewai',
    name: 'CrewAI',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://www.crewai.com',
    repoUrl: 'https://github.com/crewAIInc/crewAI',
    installCommand: 'pip install crewai',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['multi-agent', 'crew', 'framework'],
  },
  {
    slug: 'openai-swarm',
    name: 'OpenAI Swarm',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://github.com/openai/swarm',
    repoUrl: 'https://github.com/openai/swarm',
    installCommand: 'pip install git+https://github.com/openai/swarm.git',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'researchers'],
    tags: ['multi-agent', 'openai', 'experimental'],
  },
  {
    slug: 'assistant-ui',
    name: 'assistant-ui',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://www.assistant-ui.com',
    repoUrl: 'https://github.com/assistant-ui/assistant-ui',
    installCommand: 'npx assistant-ui create',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'designers'],
    tags: ['react', 'chat-ui', 'components'],
  },
  {
    slug: 'mem0',
    name: 'Mem0',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://mem0.ai',
    repoUrl: 'https://github.com/mem0ai/mem0',
    installCommand: 'pip install mem0ai',
    pricing: 'freemium',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['memory', 'agents', 'rag'],
  },
  {
    slug: 'pydantic-ai',
    name: 'Pydantic AI',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://ai.pydantic.dev',
    repoUrl: 'https://github.com/pydantic/pydantic-ai',
    installCommand: 'pip install pydantic-ai',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['python', 'agents', 'typed'],
  },
  {
    slug: 'vercel-ai-sdk',
    name: 'Vercel AI SDK',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://sdk.vercel.ai',
    repoUrl: 'https://github.com/vercel/ai',
    installCommand: 'npm i ai',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['typescript', 'react', 'streaming'],
  },
  {
    slug: 'litellm',
    name: 'LiteLLM',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://www.litellm.ai',
    repoUrl: 'https://github.com/BerriAI/litellm',
    installCommand: 'pip install litellm',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['proxy', 'multi-llm', 'gateway'],
  },
  {
    slug: 'n8n',
    name: 'n8n',
    type: 'github-repo',
    category: 'productivity',
    homepage: 'https://n8n.io',
    repoUrl: 'https://github.com/n8n-io/n8n',
    installCommand: 'npx n8n',
    pricing: 'freemium',
    bestFor: ['solo-founders', 'enterprise'],
    tags: ['automation', 'workflows', 'no-code'],
  },
  {
    slug: 'transformers',
    name: 'Transformers',
    type: 'github-repo',
    category: 'data',
    homepage: 'https://huggingface.co/docs/transformers',
    repoUrl: 'https://github.com/huggingface/transformers',
    installCommand: 'pip install transformers',
    pricing: 'open-source',
    bestFor: ['data-analysts', 'researchers'],
    tags: ['huggingface', 'nlp', 'models'],
  },
  {
    slug: 'ollama',
    name: 'Ollama',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://ollama.com',
    repoUrl: 'https://github.com/ollama/ollama',
    installCommand: 'brew install ollama',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'researchers'],
    tags: ['local-llm', 'inference', 'cli'],
  },
  {
    slug: 'comfyui',
    name: 'ComfyUI',
    type: 'github-repo',
    category: 'design',
    homepage: 'https://www.comfy.org',
    repoUrl: 'https://github.com/comfyanonymous/ComfyUI',
    installCommand: 'git clone https://github.com/comfyanonymous/ComfyUI',
    pricing: 'open-source',
    bestFor: ['designers', 'video-creators'],
    tags: ['stable-diffusion', 'image-gen', 'node-based'],
  },
  {
    slug: 'llamaindex',
    name: 'LlamaIndex',
    type: 'github-repo',
    category: 'data',
    homepage: 'https://www.llamaindex.ai',
    repoUrl: 'https://github.com/run-llama/llama_index',
    installCommand: 'pip install llama-index',
    pricing: 'open-source',
    bestFor: ['data-analysts', 'coding-agents'],
    tags: ['rag', 'indexing', 'data'],
  },
  {
    slug: 'langgraph',
    name: 'LangGraph',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://www.langchain.com/langgraph',
    repoUrl: 'https://github.com/langchain-ai/langgraph',
    installCommand: 'pip install langgraph',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['graph', 'agents', 'workflows'],
  },
  {
    slug: 'open-interpreter',
    name: 'Open Interpreter',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://openinterpreter.com',
    repoUrl: 'https://github.com/OpenInterpreter/open-interpreter',
    installCommand: 'pip install open-interpreter',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'data-analysts'],
    tags: ['interpreter', 'code-exec', 'agent'],
  },
  {
    slug: 'fastchat',
    name: 'FastChat',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://github.com/lm-sys/FastChat',
    repoUrl: 'https://github.com/lm-sys/FastChat',
    installCommand: 'pip install fschat',
    pricing: 'open-source',
    bestFor: ['researchers'],
    tags: ['serving', 'inference', 'chat'],
  },
  {
    slug: 'vllm',
    name: 'vLLM',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://docs.vllm.ai',
    repoUrl: 'https://github.com/vllm-project/vllm',
    installCommand: 'pip install vllm',
    pricing: 'open-source',
    bestFor: ['enterprise', 'researchers'],
    tags: ['serving', 'inference', 'gpu'],
  },
  {
    slug: 'whisper',
    name: 'Whisper',
    type: 'github-repo',
    category: 'voice-audio',
    homepage: 'https://openai.com/research/whisper',
    repoUrl: 'https://github.com/openai/whisper',
    installCommand: 'pip install -U openai-whisper',
    pricing: 'open-source',
    bestFor: ['content-writers', 'video-creators'],
    tags: ['speech-to-text', 'audio', 'openai'],
  },
  {
    slug: 'stable-diffusion-webui',
    name: 'Stable Diffusion WebUI',
    type: 'github-repo',
    category: 'design',
    homepage: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    repoUrl: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    installCommand: null,
    pricing: 'open-source',
    bestFor: ['designers'],
    tags: ['stable-diffusion', 'image-gen', 'webui'],
  },
  {
    slug: 'agno',
    name: 'Agno',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://www.agno.com',
    repoUrl: 'https://github.com/agno-agi/agno',
    installCommand: 'pip install agno',
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['agents', 'framework', 'python'],
  },
  {
    slug: 'dify',
    name: 'Dify',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://dify.ai',
    repoUrl: 'https://github.com/langgenius/dify',
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['solo-founders', 'enterprise'],
    tags: ['llm-ops', 'workflows', 'platform'],
  },
  {
    slug: 'flowise',
    name: 'Flowise',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://flowiseai.com',
    repoUrl: 'https://github.com/FlowiseAI/Flowise',
    installCommand: 'npm install -g flowise',
    pricing: 'open-source',
    bestFor: ['solo-founders'],
    tags: ['visual', 'no-code', 'llm'],
  },
  {
    slug: 'haystack',
    name: 'Haystack',
    type: 'github-repo',
    category: 'data',
    homepage: 'https://haystack.deepset.ai',
    repoUrl: 'https://github.com/deepset-ai/haystack',
    installCommand: 'pip install haystack-ai',
    pricing: 'open-source',
    bestFor: ['data-analysts', 'enterprise'],
    tags: ['rag', 'search', 'framework'],
  },
  {
    slug: 'guidance',
    name: 'Guidance',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://github.com/guidance-ai/guidance',
    repoUrl: 'https://github.com/guidance-ai/guidance',
    installCommand: 'pip install guidance',
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['constrained-gen', 'prompting', 'llm'],
  },
  {
    slug: 'dspy',
    name: 'DSPy',
    type: 'github-repo',
    category: 'research',
    homepage: 'https://dspy.ai',
    repoUrl: 'https://github.com/stanfordnlp/dspy',
    installCommand: 'pip install dspy',
    pricing: 'open-source',
    bestFor: ['researchers', 'coding-agents'],
    tags: ['stanford', 'prompting', 'optimization'],
  },
  {
    slug: 'autogpt',
    name: 'AutoGPT',
    type: 'github-repo',
    category: 'agents',
    homepage: 'https://agpt.co',
    repoUrl: 'https://github.com/Significant-Gravitas/AutoGPT',
    installCommand: null,
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['autonomous', 'agent', 'gpt'],
  },
  {
    slug: 'gpt-engineer',
    name: 'GPT Engineer',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://gptengineer.app',
    repoUrl: 'https://github.com/gpt-engineer-org/gpt-engineer',
    installCommand: 'pip install gpt-engineer',
    pricing: 'open-source',
    bestFor: ['solo-founders', 'coding-agents'],
    tags: ['code-gen', 'agent', 'cli'],
  },
  {
    slug: 'aider',
    name: 'Aider',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://aider.chat',
    repoUrl: 'https://github.com/Aider-AI/aider',
    installCommand: 'pip install aider-chat',
    pricing: 'open-source',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['cli', 'pair-programming', 'git'],
  },
  {
    slug: 'continue',
    name: 'Continue',
    type: 'github-repo',
    category: 'coding',
    homepage: 'https://continue.dev',
    repoUrl: 'https://github.com/continuedev/continue',
    installCommand: null,
    pricing: 'open-source',
    bestFor: ['coding-agents'],
    tags: ['ide', 'vscode', 'jetbrains'],
  },

  // ─── 25 LLM / AI products ─────────────────────────────────────────────────
  {
    slug: 'cursor',
    name: 'Cursor',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://cursor.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['ide', 'editor', 'pair-programming'],
  },
  {
    slug: 'windsurf',
    name: 'Windsurf',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://windsurf.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['coding-agents', 'solo-founders'],
    tags: ['ide', 'editor', 'agentic'],
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    type: 'llm-product',
    category: 'research',
    homepage: 'https://www.perplexity.ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['researchers', 'content-writers'],
    tags: ['search', 'research', 'answer-engine'],
  },
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://www.notion.so/product/ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['content-writers', 'solo-founders'],
    tags: ['notion', 'writing', 'productivity'],
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    type: 'llm-product',
    category: 'voice-audio',
    homepage: 'https://elevenlabs.io',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'content-writers'],
    tags: ['tts', 'voice', 'cloning'],
  },
  {
    slug: 'midjourney',
    name: 'Midjourney',
    type: 'llm-product',
    category: 'design',
    homepage: 'https://www.midjourney.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['designers', 'marketers'],
    tags: ['image-gen', 'art', 'discord'],
  },
  {
    slug: 'suno',
    name: 'Suno',
    type: 'llm-product',
    category: 'voice-audio',
    homepage: 'https://suno.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'marketers'],
    tags: ['music', 'generation', 'songs'],
  },
  {
    slug: 'runway',
    name: 'Runway',
    type: 'llm-product',
    category: 'video',
    homepage: 'https://runwayml.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'designers'],
    tags: ['video-gen', 'editing', 'gen-3'],
  },
  {
    slug: 'v0',
    name: 'v0 by Vercel',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://v0.dev',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['designers', 'solo-founders'],
    tags: ['ui-gen', 'react', 'vercel'],
  },
  {
    slug: 'lovable',
    name: 'Lovable',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://lovable.dev',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['solo-founders', 'designers'],
    tags: ['app-builder', 'no-code', 'fullstack'],
  },
  {
    slug: 'bolt-new',
    name: 'Bolt.new',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://bolt.new',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['solo-founders', 'coding-agents'],
    tags: ['stackblitz', 'webapp', 'prototyping'],
  },
  {
    slug: 'replit-agent',
    name: 'Replit Agent',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://replit.com/site/agent',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['solo-founders', 'students'],
    tags: ['replit', 'agent', 'cloud-ide'],
  },
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://chatgpt.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['content-writers', 'students'],
    tags: ['openai', 'chat', 'assistant'],
  },
  {
    slug: 'gemini',
    name: 'Gemini',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://gemini.google.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['researchers', 'content-writers'],
    tags: ['google', 'multimodal', 'chat'],
  },
  {
    slug: 'claude-ai',
    name: 'Claude.ai',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://claude.ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['content-writers', 'researchers'],
    tags: ['anthropic', 'chat', 'assistant'],
  },
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    type: 'llm-product',
    category: 'coding',
    homepage: 'https://github.com/features/copilot',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['coding-agents', 'enterprise'],
    tags: ['copilot', 'completions', 'github'],
  },
  {
    slug: 'jasper',
    name: 'Jasper',
    type: 'llm-product',
    category: 'marketing',
    homepage: 'https://www.jasper.ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'paid',
    bestFor: ['marketers', 'content-writers'],
    tags: ['copywriting', 'marketing', 'brand'],
  },
  {
    slug: 'copy-ai',
    name: 'Copy.ai',
    type: 'llm-product',
    category: 'marketing',
    homepage: 'https://www.copy.ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['marketers', 'content-writers'],
    tags: ['copywriting', 'go-to-market', 'sales'],
  },
  {
    slug: 'descript',
    name: 'Descript',
    type: 'llm-product',
    category: 'video',
    homepage: 'https://www.descript.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'content-writers'],
    tags: ['video', 'transcription', 'editing'],
  },
  {
    slug: 'pika',
    name: 'Pika',
    type: 'llm-product',
    category: 'video',
    homepage: 'https://pika.art',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'designers'],
    tags: ['video-gen', 'pika', 'ai-video'],
  },
  {
    slug: 'heygen',
    name: 'HeyGen',
    type: 'llm-product',
    category: 'video',
    homepage: 'https://www.heygen.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['video-creators', 'marketers'],
    tags: ['avatars', 'video', 'translation'],
  },
  {
    slug: 'deepl',
    name: 'DeepL',
    type: 'llm-product',
    category: 'translation',
    homepage: 'https://www.deepl.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['hebrew-speakers', 'content-writers'],
    tags: ['translation', 'localization', 'nlp'],
  },
  {
    slug: 'gamma',
    name: 'Gamma',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://gamma.app',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['solo-founders', 'marketers'],
    tags: ['presentations', 'slides', 'ai'],
  },
  {
    slug: 'tldraw-make-real',
    name: 'tldraw Make Real',
    type: 'llm-product',
    category: 'design',
    homepage: 'https://makereal.tldraw.com',
    repoUrl: null,
    installCommand: null,
    pricing: 'free',
    bestFor: ['designers', 'coding-agents'],
    tags: ['design-to-code', 'tldraw', 'prototyping'],
  },
  {
    slug: 'mistral-le-chat',
    name: 'Mistral Le Chat',
    type: 'llm-product',
    category: 'productivity',
    homepage: 'https://chat.mistral.ai',
    repoUrl: null,
    installCommand: null,
    pricing: 'freemium',
    bestFor: ['researchers', 'enterprise'],
    tags: ['mistral', 'chat', 'europe'],
  },
];

// ─── Trending-score heuristic ───────────────────────────────────────────────
// Initial score before live GitHub metrics refresh. Bumped for marquee tools.
const TOP_TIER = new Set([
  'claude-code', 'claude-agent-sdk', 'claude-mcp', 'cursor', 'langchain',
  'ollama', 'crewai', 'vercel-ai-sdk', 'comfyui', 'github-copilot',
  'perplexity', 'elevenlabs', 'midjourney', 'mcp-github', 'mcp-slack',
]);

function initialTrendingScore(tool) {
  if (TOP_TIER.has(tool.slug)) return 90;
  switch (tool.type) {
    case 'claude-skill':  return 78;
    case 'mcp-connector': return 70;
    case 'github-repo':   return 72;
    case 'llm-product':   return 74;
    case 'agent-framework': return 75;
    default: return 65;
  }
}

module.exports = { CATALOG, initialTrendingScore };
