/**
 * carouselGenerator.js
 * ---------------------------------------------------------------------------
 * Renders Instagram comparison-carousel slides via Remotion Lambda, with
 * full-bleed AI backgrounds from Gemini's `gemini-2.5-flash-image-preview`
 * (a.k.a. Nano Banana) and Hebrew copy generated by Gemini in the site's
 * editorial voice.
 *
 * Output format: 1080×1350 (Instagram-preferred 4:5 portrait).
 *
 * Public API:
 *   buildCarouselSlideUrls(comparisons) → string[]  (public HTTPS PNG URLs in slide order)
 */

const admin = require('firebase-admin');
const { renderStillOnLambda } = require('@remotion/lambda/client');
const { v4: uuidv4 } = require('uuid');
const { logger } = require('../config');
const { loadGeminiSDK, getGeminiSDK } = require('../utils');

// Secret Manager occasionally injects trailing whitespace into env values,
// which then bleeds into the AWS Authorization header → "Invalid character
// in header content". Same workaround as functions/youtubePipeline.js.
function trimAwsCreds() {
  if (process.env.REMOTION_AWS_ACCESS_KEY_ID) {
    process.env.REMOTION_AWS_ACCESS_KEY_ID = process.env.REMOTION_AWS_ACCESS_KEY_ID.trim();
  }
  if (process.env.REMOTION_AWS_SECRET_ACCESS_KEY) {
    process.env.REMOTION_AWS_SECRET_ACCESS_KEY = process.env.REMOTION_AWS_SECRET_ACCESS_KEY.trim();
  }
}

const REGION = 'us-east-1';
const FUNCTION_NAME = 'remotion-render-4-0-452-mem3008mb-disk2048mb-900sec';
const SERVE_URL =
  'https://remotionlambda-useast1-di0xuqpokc.s3.us-east-1.amazonaws.com/sites/trending-tech-daily/index.html';

// ─── Gemini helpers ────────────────────────────────────────────────────────
async function getGenAI() {
  if (!process.env.GEMINI_API_KEY) return null;
  await loadGeminiSDK();
  const { GoogleGenAI } = getGeminiSDK();
  if (!GoogleGenAI) return null;
  return new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
}

/**
 * Nano Banana — generate a stylised photographic background and return a
 * public HTTPS URL (uploaded to Firebase Storage). null on failure.
 */
async function generateBananaBackground(genAI, prompt, runId, slideKey) {
  if (!genAI) return null;
  try {
    // "Nano Banana" — Google's image-gen model line. We use the stable
    // gemini-2.5-flash-image (a.k.a. Nano Banana) for predictable quality;
    // upgrade to `nano-banana-pro-preview` later for premium runs if desired.
    const result = await genAI.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
    });
    const parts =
      (result &&
        result.candidates &&
        result.candidates[0] &&
        result.candidates[0].content &&
        result.candidates[0].content.parts) ||
      [];
    for (const p of parts) {
      if (p.inlineData && p.inlineData.data) {
        const buf = Buffer.from(p.inlineData.data, 'base64');
        const bucket = admin.storage().bucket();
        const dest = `instagram/carousel/${runId}/bg_${slideKey}_${uuidv4()}.png`;
        const file = bucket.file(dest);
        await file.save(buf, {
          contentType: p.inlineData.mimeType || 'image/png',
          resumable: false,
          public: true,
          metadata: { cacheControl: 'public, max-age=86400' },
        });
        try { await file.makePublic(); } catch (e) { /* save() already public */ }
        return `https://storage.googleapis.com/${bucket.name}/${dest}`;
      }
    }
    logger.warn('Nano Banana returned no image parts for', slideKey);
    return null;
  } catch (err) {
    logger.warn(`Nano Banana failed for ${slideKey}:`, err.message);
    return null;
  }
}

/**
 * Ask Gemini to produce punchy Hebrew copy for the whole carousel.
 * Returns an object with cover headline/sub + a hook+verdict+winner per comparison.
 * Falls back to comparison.title / comparison.verdict on failure.
 */
async function generateCopy(genAI, comparisons) {
  const fallback = {
    coverHeadline: 'השוואות השבוע',
    coverSubline: 'הניתוחים שאתם חייבים לקרוא לפני שאתם קונים',
    ctaHeadline: 'רוצים את הניתוח המלא?',
    ctaSubline: 'מפרט מלא, יתרונות, חסרונות וטבלת השוואה — באתר',
    slides: comparisons.map((c) => ({
      hook: `${c.itemA} או ${c.itemB}?`,
      verdict: (c.verdict || '').slice(0, 200),
      winner: 'tie',
    })),
  };

  if (!genAI) return fallback;

  const list = comparisons
    .map((c, i) => `${i + 1}. ${c.itemA} מול ${c.itemB}\n   verdict: ${(c.verdict || '').slice(0, 280)}`)
    .join('\n');

  const prompt = `אתה עורך תוכן בכיר ב-TrendingTechDaily — אתר חדשות טכנולוגיה בעברית. עליך לכתוב את הקופי לקרוסלת אינסטגרם שמסכמת ${comparisons.length} השוואות מוצרים.

הסגנון: עברית עיתונאית רהוטה, חדה, וטרנדית. כתיב מלא (עם וא"ו ויו"ד). אסור להשתמש באנגלית מעבר לשמות מוצרים/חברות. כל משפט קצר, אנרגטי, וכזה שמתאים לקרוסלה באינסטגרם — קצר, חד ומסקרן.

ההשוואות:
${list}

החזר JSON בלבד (ללא markdown) במבנה:
{
  "coverHeadline": "כותרת ראשית לסלייד הפתיחה — 2-4 מילים, מסקרנת, אנרגטית",
  "coverSubline": "שורת משנה לסלייד הפתיחה — 6-10 מילים, מבטיחה ערך לקורא",
  "ctaHeadline": "כותרת לסלייד הסיום — 3-5 מילים שמדרבנות לקליק לאתר",
  "ctaSubline": "שורת משנה לסיום — 8-12 מילים, מסבירה למה לקרוא באתר",
  "slides": [
    {
      "hook": "שורת פתיחה לסלייד ההשוואה — 5-9 מילים, מסקרנת ('מי הפלאפון שכדאי לכם השנה?')",
      "verdict": "השורה התחתונה — 14-22 מילים, חדה, ברורה, מסכמת את ההמלצה",
      "winner": "A או B או tie"
    }
    // אחד לכל השוואה, באותו הסדר
  ]
}`;

  try {
    const result = await genAI.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
    });
    const raw = (result.text && (typeof result.text === 'function' ? result.text() : result.text)) || '';
    const m = String(raw).match(/\{[\s\S]*\}/);
    if (!m) return fallback;
    const parsed = JSON.parse(m[0]);
    if (!parsed || typeof parsed !== 'object') return fallback;
    return {
      coverHeadline: parsed.coverHeadline || fallback.coverHeadline,
      coverSubline: parsed.coverSubline || fallback.coverSubline,
      ctaHeadline: parsed.ctaHeadline || fallback.ctaHeadline,
      ctaSubline: parsed.ctaSubline || fallback.ctaSubline,
      slides: Array.isArray(parsed.slides) && parsed.slides.length === comparisons.length
        ? parsed.slides.map((s, i) => ({
            hook: (s.hook && String(s.hook).trim()) || fallback.slides[i].hook,
            verdict: (s.verdict && String(s.verdict).trim()) || fallback.slides[i].verdict,
            winner: ['A', 'B', 'tie'].includes(s.winner) ? s.winner : 'tie',
          }))
        : fallback.slides,
    };
  } catch (err) {
    logger.warn('generateCopy failed, using fallback:', err.message);
    return fallback;
  }
}

/**
 * Render one Remotion still on Lambda with the given inputProps and return
 * the public PNG URL.
 */
async function renderSlide(compositionId, inputProps) {
  trimAwsCreds();
  const { url } = await renderStillOnLambda({
    region: REGION,
    functionName: FUNCTION_NAME,
    serveUrl: SERVE_URL,
    composition: compositionId,
    inputProps,
    imageFormat: 'png',
    privacy: 'public',
    maxRetries: 2,
  });
  return url;
}

// ─── prompts ───────────────────────────────────────────────────────────────
function coverPrompt(comparisons) {
  const subjects = comparisons.slice(0, 4).map((c) => `${c.itemA} and ${c.itemB}`).join(', ');
  return (
    `Editorial photographic background image, 4:5 portrait, ` +
    `vibrant cinematic tech magazine cover aesthetic. Subject hints: ${subjects}. ` +
    `Composition: dark dramatic studio backdrop with bold neon accent lighting in deep blue and emerald green, ` +
    `subtle product silhouettes blurred in the background, soft bokeh, premium feel. ` +
    `NO text, NO logos, NO watermarks, NO product brand names visible. ` +
    `Negative space concentrated bottom-right for text overlay.`
  );
}

function comparisonPrompt(itemA, itemB) {
  return (
    `Cinematic split-screen tech photography, 4:5 portrait, two products facing off. ` +
    `Top half: dramatic side-lit shot evoking "${itemA}" category. ` +
    `Bottom half: dramatic side-lit shot evoking "${itemB}" category. ` +
    `Style: hyper-modern, vivid color grading, subtle glow, sharp focus on hero objects, ` +
    `deep contrast background, premium gadget magazine look. ` +
    `NO text, NO logos, NO brand names. Center is dark for text overlay.`
  );
}

function ctaPrompt() {
  return (
    `Abstract vibrant tech background, 4:5 portrait. ` +
    `Glowing neon blue (#2196F3) and emerald green (#4CAF50) waves of light on a near-black backdrop, ` +
    `soft gradient mesh, particle bokeh, futuristic feel. ` +
    `NO text, NO logos, NO watermarks. Clean center for text overlay.`
  );
}

// ─── public ────────────────────────────────────────────────────────────────
/**
 * Generate every slide of one carousel and return their public PNG URLs.
 *
 * @param {Array<{itemA:string,itemB:string,verdict?:string,title?:string}>} comparisons
 * @returns {Promise<{ urls: string[], copy: object }>}
 */
async function buildCarouselSlideUrls(comparisons) {
  if (!comparisons || !comparisons.length) {
    throw new Error('buildCarouselSlideUrls: no comparisons provided');
  }

  const runId = `igcar_${Date.now()}_${uuidv4().slice(0, 8)}`;
  const genAI = await getGenAI();

  // 1. Generate Hebrew copy + every background in parallel.
  const totalSteps = comparisons.length + 2; // cover + N + cta
  logger.info(`[carouselGenerator] generating copy + ${totalSteps} backgrounds…`);

  const [copy, coverBg, ctaBg, ...comparisonBgs] = await Promise.all([
    generateCopy(genAI, comparisons),
    generateBananaBackground(genAI, coverPrompt(comparisons), runId, 'cover'),
    generateBananaBackground(genAI, ctaPrompt(), runId, 'cta'),
    ...comparisons.map((c, i) =>
      generateBananaBackground(genAI, comparisonPrompt(c.itemA, c.itemB), runId, `cmp${i + 1}`)
    ),
  ]);

  logger.info(`[carouselGenerator] backgrounds: cover=${!!coverBg} cta=${!!ctaBg} comparisons=${comparisonBgs.filter(Boolean).length}/${comparisons.length}`);

  // 2. Render each slide on Lambda in parallel (each is a quick single-frame still).
  const slideJobs = [];
  slideJobs.push(
    renderSlide('IGCoverSlide', {
      bgUrl: coverBg || undefined,
      headline: copy.coverHeadline,
      subline: copy.coverSubline,
      totalCount: comparisons.length,
    })
  );
  comparisons.forEach((c, i) => {
    const sCopy = copy.slides[i] || { hook: '', verdict: '', winner: 'tie' };
    slideJobs.push(
      renderSlide('IGComparisonSlide', {
        bgUrl: comparisonBgs[i] || undefined,
        index: i + 1,
        totalSteps,
        itemA: c.itemA,
        itemB: c.itemB,
        hook: sCopy.hook,
        verdict: sCopy.verdict,
        winner: sCopy.winner,
      })
    );
  });
  slideJobs.push(
    renderSlide('IGCTASlide', {
      bgUrl: ctaBg || undefined,
      // Brand-consistent CTA — kept fixed (not Gemini-generated) per editorial direction
      headline: 'ההשוואות המלאות באתר',
      subline: 'צללו לפרטים',
    })
  );

  const urls = await Promise.all(slideJobs);
  logger.info(`[carouselGenerator] rendered ${urls.length} stills on Lambda`);

  return { urls, copy };
}

module.exports = {
  buildCarouselSlideUrls,
  renderSlide,
};
