/**
 * aiGlossary.js
 * ---------------------------------------------------------------------------
 * Business logic for the AI Glossary (ai_glossary collection).
 *
 * Exports:
 *   - seedAiGlossary({ force })
 *   - getAiGlossary({ language })
 *   - getAiGlossaryTerm(slug)
 *
 * Docs are keyed by slug. English copy is hardcoded in GLOSSARY_TERMS;
 * Hebrew copy is generated by Gemini at seed time (one batched call per
 * term, bounded concurrency, exponential backoff).
 */

const admin = require('firebase-admin');
const { db, logger } = require('./config');
const { loadGeminiSDK, getGeminiSDK } = require('./utils');

const COLL = 'ai_glossary';
const MODEL = 'gemini-2.5-flash';

const CATEGORY_ORDER = { core: 0, models: 1, agents: 2, developer: 3 };

function sleep(ms) { return new Promise((r) => setTimeout(r, ms)); }

async function getGenAI() {
  if (!process.env.GEMINI_API_KEY) throw new Error('GEMINI_API_KEY is not set');
  await loadGeminiSDK();
  const { GoogleGenAI } = getGeminiSDK();
  if (!GoogleGenAI) throw new Error('Gemini SDK failed to load');
  return new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
}

async function pMap(items, mapper, concurrency = 4) {
  const results = new Array(items.length);
  let idx = 0;
  const workers = new Array(Math.min(concurrency, items.length)).fill(0).map(async () => {
    for (;;) {
      const i = idx++;
      if (i >= items.length) return;
      try { results[i] = { ok: true, value: await mapper(items[i], i) }; }
      catch (err) { results[i] = { ok: false, error: err }; }
    }
  });
  await Promise.all(workers);
  return results;
}

function parseJsonLoose(text) {
  if (!text) return null;
  let s = String(text).trim();
  s = s.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
  const first = s.indexOf('{');
  const last = s.lastIndexOf('}');
  if (first !== -1 && last !== -1 && last > first) s = s.slice(first, last + 1);
  try { return JSON.parse(s); } catch (_) { return null; }
}

function isRetryable(err) {
  const msg = String(err && err.message || '');
  if (/429|rate.?limit|RESOURCE_EXHAUSTED|quota/i.test(msg)) return true;
  if (/5\d\d|UNAVAILABLE|INTERNAL|DEADLINE_EXCEEDED|ECONNRESET|ETIMEDOUT/i.test(msg)) return true;
  return false;
}

// ── Hardcoded 35-entry glossary ────────────────────────────────────────────
// term_he and definition_he are filled by Gemini at seed time.
const GLOSSARY_TERMS = [
  // ── core (15) ───────────────────────────────────────────────────────────
  { slug: 'ai', category: 'core', order: 1, term_en: 'AI (Artificial Intelligence)',
    aliases: ['artificial intelligence'],
    definition_en: 'AI is software that performs tasks people usually associate with human thinking — like understanding language, recognizing images, or making decisions. Modern AI mostly means systems trained on large amounts of data to spot patterns. When you chat with a tool like ChatGPT or Claude, you are using AI.' },
  { slug: 'agi', category: 'core', order: 2, term_en: 'AGI (Artificial General Intelligence)',
    aliases: ['general ai', 'strong ai'],
    definition_en: 'AGI is the hypothetical idea of an AI that can do any intellectual task a human can — not just one specific job. Today, no system has reached AGI. Most current tools are narrow: they are great at one thing (writing, coding, summarizing) and weak everywhere else.' },
  { slug: 'machine-learning', category: 'core', order: 3, term_en: 'Machine Learning',
    aliases: ['ml'],
    definition_en: 'Machine learning is how computers learn from examples instead of following hand-written rules. You feed the system lots of data, and it figures out the patterns on its own. It is the engine behind almost every AI product you use today.' },
  { slug: 'deep-learning', category: 'core', order: 4, term_en: 'Deep Learning',
    aliases: [],
    definition_en: 'Deep learning is a type of machine learning that uses neural networks with many layers. The "deep" part refers to the number of layers — more layers let the model learn more complex patterns. This is what powers image recognition, voice assistants, and modern language models.' },
  { slug: 'neural-network', category: 'core', order: 5, term_en: 'Neural Network',
    aliases: ['artificial neural network'],
    definition_en: 'A neural network is a math structure loosely inspired by the brain. It is made of layers of simple units (neurons) that pass numbers to each other. By tweaking the connections during training, the network learns to turn inputs (like text) into useful outputs (like an answer).' },
  { slug: 'inference', category: 'core', order: 6, term_en: 'Inference',
    aliases: [],
    definition_en: 'Inference is when you actually use a trained AI model to get an answer. Training is the long, expensive learning phase; inference is the fast, cheap "ask a question, get a response" part. Every time you press send in ChatGPT, you trigger an inference.' },
  { slug: 'training', category: 'core', order: 7, term_en: 'Training',
    aliases: [],
    definition_en: 'Training is the process of teaching a model by showing it huge amounts of data and adjusting its internal numbers until it gets better at predicting the right answer. It can take weeks and cost millions of dollars for large models. Once trained, the model is frozen and ready to use.' },
  { slug: 'prompt', category: 'core', order: 8, term_en: 'Prompt',
    aliases: [],
    definition_en: 'A prompt is whatever you type or send to an AI model — your question, instruction, or context. Better prompts usually produce better answers. Skilled prompting is part wording, part structure, and part knowing what context to include.' },
  { slug: 'context-window', category: 'core', order: 9, term_en: 'Context Window',
    aliases: ['context length'],
    definition_en: 'The context window is the maximum amount of text the model can "see" at once — your prompt, plus the conversation history, plus any documents you attach. Measured in tokens. Once you exceed it, the model starts forgetting the earliest parts.' },
  { slug: 'token', category: 'core', order: 10, term_en: 'Token',
    aliases: [],
    definition_en: 'Tokens are the small chunks of text that language models actually read and write. A token can be a whole word, part of a word, or just a few characters. One English word is roughly 1.3 tokens. Models charge by tokens, and context windows are measured in tokens.' },
  { slug: 'embedding', category: 'core', order: 11, term_en: 'Embedding',
    aliases: ['vector embedding'],
    definition_en: 'An embedding is a list of numbers that represents the meaning of a piece of text (or image, or audio). Similar meanings get similar numbers. This is how AI compares things for search, recommendations, and matching — by checking how close their embeddings are.' },
  { slug: 'vector-database', category: 'core', order: 12, term_en: 'Vector Database',
    aliases: ['vector db', 'vector store'],
    definition_en: 'A vector database stores embeddings and lets you search for items by meaning rather than by exact words. Ask for "cheap fast laptops" and it can find products described as "affordable speedy notebooks." Vector DBs power the search behind most modern AI assistants.' },
  { slug: 'hallucination', category: 'core', order: 13, term_en: 'Hallucination',
    aliases: [],
    definition_en: 'A hallucination is when an AI confidently states something that is wrong or made up — a fake citation, a fabricated quote, a function that does not exist. It happens because models predict plausible text, not verified facts. Always double-check important details.' },
  { slug: 'temperature', category: 'core', order: 14, term_en: 'Temperature',
    aliases: [],
    definition_en: 'Temperature is a setting that controls how creative or predictable the model is. Low temperature (near 0) gives consistent, focused answers — good for code or facts. High temperature (near 1) gives more varied, creative answers — good for brainstorming or fiction.' },
  { slug: 'top-p', category: 'core', order: 15, term_en: 'Top-p (Nucleus Sampling)',
    aliases: ['nucleus sampling'],
    definition_en: 'Top-p is another creativity dial. Instead of considering every possible next word, the model only picks from the top words that together cover p percent of the probability. Lower top-p means safer answers; higher top-p means more variety. Usually you tune temperature or top-p, not both.' },

  // ── models (9) ──────────────────────────────────────────────────────────
  { slug: 'llm', category: 'models', order: 1, term_en: 'LLM (Large Language Model)',
    aliases: ['large language model'],
    definition_en: 'An LLM is a big AI model trained on huge amounts of text to predict the next word. From that simple task it learns grammar, facts, reasoning patterns, and even coding. GPT-4, Claude, and Gemini are all LLMs. They power most chat assistants you have heard of.' },
  { slug: 'foundation-model', category: 'models', order: 2, term_en: 'Foundation Model',
    aliases: [],
    definition_en: 'A foundation model is a large model trained on broad data that can be adapted for many tasks — chat, summarization, classification, coding, and so on. The "foundation" part means you build other products on top of it instead of training from scratch every time.' },
  { slug: 'multimodal-model', category: 'models', order: 3, term_en: 'Multimodal Model',
    aliases: ['multimodal'],
    definition_en: 'A multimodal model handles more than just text — it can also read images, listen to audio, or watch video. You can paste a screenshot, ask "what is wrong here," and get an answer. GPT-4o, Claude, and Gemini are multimodal.' },
  { slug: 'open-weights', category: 'models', order: 4, term_en: 'Open-Weights Model',
    aliases: ['open weights', 'open model'],
    definition_en: 'An open-weights model is one whose trained parameters are publicly downloadable, so you can run it yourself on your own hardware. Llama and Mistral are well-known examples. "Open weights" is not always the same as full open-source — the training data and code may still be private.' },
  { slug: 'closed-source-model', category: 'models', order: 5, term_en: 'Closed-Source Model',
    aliases: ['closed model', 'proprietary model'],
    definition_en: 'A closed-source model is only accessible through an API or product — you cannot download the weights or run it on your own machine. GPT-4 and Claude are closed-source. You usually get higher quality and zero ops, but you depend on the provider and pay per use.' },
  { slug: 'fine-tuning', category: 'models', order: 6, term_en: 'Fine-Tuning',
    aliases: ['finetune'],
    definition_en: 'Fine-tuning is taking a general model and training it a bit more on your own data so it specializes in your task — your tone, your domain, your formats. It needs less data and money than training from scratch, but more than just writing a clever prompt.' },
  { slug: 'lora', category: 'models', order: 7, term_en: 'LoRA',
    aliases: ['low-rank adaptation'],
    definition_en: 'LoRA is a cheap, fast way to fine-tune a model. Instead of retraining the whole thing, you train tiny "adapter" layers that nudge its behavior. The result is small (megabytes, not gigabytes), quick to swap, and good enough for most personalization tasks.' },
  { slug: 'distillation', category: 'models', order: 8, term_en: 'Distillation',
    aliases: ['model distillation'],
    definition_en: 'Distillation is training a smaller, faster "student" model to copy a bigger "teacher" model. The student ends up much cheaper to run while keeping most of the quality. This is how providers ship fast, low-cost variants of their flagship models.' },
  { slug: 'rlhf', category: 'models', order: 9, term_en: 'RLHF',
    aliases: ['reinforcement learning from human feedback'],
    definition_en: 'RLHF is a training trick where humans rate model answers, and the model learns to prefer the ones humans like. It is the main reason modern chat models sound polite, helpful, and less likely to go off the rails. Most flagship LLMs use some form of RLHF.' },

  // ── agents (8) ──────────────────────────────────────────────────────────
  { slug: 'ai-agent', category: 'agents', order: 1, term_en: 'AI Agent',
    aliases: ['agent'],
    definition_en: 'An AI agent is an AI system that does not just answer — it acts. It can plan steps, call tools, read files, browse the web, and check its own work, all to complete a goal you give it. Think of it as an LLM with hands.' },
  { slug: 'agentic-ai', category: 'agents', order: 2, term_en: 'Agentic AI',
    aliases: ['agentic'],
    definition_en: 'Agentic AI is the umbrella term for AI systems that take multi-step actions on their own. The "agentic" part means the system decides what to do next rather than waiting for you to spell it out. Coding assistants, research bots, and workflow runners are all agentic.' },
  { slug: 'tool-use', category: 'agents', order: 3, term_en: 'Tool Use',
    aliases: [],
    definition_en: 'Tool use is when an AI model calls outside services to get things done — a calculator, a database, a web search, an email API. The model picks the right tool, fills in the inputs, and uses the result to keep working. This is what turns a chatbot into an agent.' },
  { slug: 'function-calling', category: 'agents', order: 4, term_en: 'Function Calling',
    aliases: [],
    definition_en: 'Function calling is the structured way a model asks to use a tool. Instead of describing the action in words, it outputs a clean JSON object that names a function and its arguments. Your code runs the function and feeds the result back. It is the plumbing behind reliable agents.' },
  { slug: 'mcp', category: 'agents', order: 5, term_en: 'MCP (Model Context Protocol)',
    aliases: ['model context protocol'],
    definition_en: 'MCP is an open standard for connecting AI assistants to outside tools and data — like a USB-C port for AI. Built by Anthropic, it lets one connector work with any MCP-compatible assistant. Slack, GitHub, your filesystem, your database — all reachable through the same protocol.' },
  { slug: 'react', category: 'agents', order: 6, term_en: 'ReAct',
    aliases: ['reason and act'],
    definition_en: 'ReAct (Reason + Act) is a popular agent pattern where the model alternates between thinking out loud ("I should search for X") and taking an action ("call search tool"). The visible reasoning step makes the agent more reliable and easier to debug.' },
  { slug: 'chain-of-thought', category: 'agents', order: 7, term_en: 'Chain of Thought',
    aliases: ['cot'],
    definition_en: 'Chain of thought is when a model writes out its step-by-step reasoning before giving the final answer. For math, logic, and multi-step problems, this dramatically improves accuracy. You will see it as "Let me think about this step by step..." in many modern assistants.' },
  { slug: 'memory', category: 'agents', order: 8, term_en: 'Memory',
    aliases: ['agent memory'],
    definition_en: 'Memory is how an AI remembers things across messages or sessions — your preferences, past projects, ongoing tasks. Short-term memory lives in the context window; long-term memory is stored in a database and pulled back in when relevant.' },

  // ── developer (5) ──────────────────────────────────────────────────────
  { slug: 'rag', category: 'developer', order: 1, term_en: 'RAG (Retrieval-Augmented Generation)',
    aliases: ['retrieval augmented generation'],
    definition_en: 'RAG is a pattern where the AI first looks up relevant information (from your docs, a database, the web) and then uses that material to write the answer. It cuts hallucinations and lets the model talk about content it was never trained on — like your private company data.' },
  { slug: 'vector-search', category: 'developer', order: 2, term_en: 'Vector Search',
    aliases: ['semantic search'],
    definition_en: 'Vector search finds results by meaning instead of exact keywords. It compares the embedding of your query to the embeddings of all stored items and returns the closest matches. It is the search engine behind most RAG systems.' },
  { slug: 'system-prompt', category: 'developer', order: 3, term_en: 'System Prompt',
    aliases: ['system message'],
    definition_en: 'A system prompt is the hidden instruction at the start of a conversation that tells the model who it is and how to behave — tone, rules, allowed topics, output format. Users do not see it, but it shapes every reply.' },
  { slug: 'chunking', category: 'developer', order: 4, term_en: 'Chunking',
    aliases: [],
    definition_en: 'Chunking is splitting a long document into smaller pieces before storing it for retrieval. Smaller chunks make search more precise; bigger chunks keep more context. Picking the right chunk size is one of the unsung crafts of building good RAG systems.' },
  { slug: 'prompt-engineering', category: 'developer', order: 5, term_en: 'Prompt Engineering',
    aliases: [],
    definition_en: 'Prompt engineering is the craft of writing inputs that get the most useful outputs from an AI model. It includes things like giving examples, defining a role, specifying the output format, and breaking big tasks into smaller steps. Half writing, half experimentation.' },
];

function buildHePrompt(term_en, definition_en) {
  return `Translate this AI/tech glossary entry to Hebrew. Return JSON with EXACTLY these keys:
- term_he: the term in natural Hebrew (keep widely-used English acronyms like LLM, MCP, RAG, LoRA, AGI as-is; can add parenthetical Hebrew explanation)
- definition_he: a natural Hebrew translation (NOT literal) of the definition, same length and tone, plain language, no markdown, no emoji

ENGLISH TERM: ${term_en}
ENGLISH DEFINITION: ${definition_en}

Output ONLY the JSON object. No commentary, no code fences.`;
}

async function translateOne(genAI, term, maxRetries = 4) {
  const prompt = buildHePrompt(term.term_en, term.definition_en);
  let lastErr;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const res = await genAI.models.generateContent({
        model: MODEL,
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        config: { temperature: 0.4, responseMimeType: 'application/json' },
      });
      const text = (res && (res.text || (res.response && res.response.text && res.response.text()))) || '';
      const parsed = parseJsonLoose(text);
      if (!parsed) throw new Error('aiGlossary: failed to parse JSON');
      const term_he = String(parsed.term_he || '').trim();
      const definition_he = String(parsed.definition_he || '').trim();
      if (!term_he || !definition_he) throw new Error('aiGlossary: missing Hebrew fields');
      return { term_he, definition_he };
    } catch (err) {
      lastErr = err;
      if (attempt >= maxRetries || !isRetryable(err)) {
        logger.warn(`[aiGlossary] translate failed for ${term.slug}: ${err.message}`);
        throw err;
      }
      const backoff = Math.min(30000, 1000 * Math.pow(2, attempt)) + Math.floor(Math.random() * 500);
      await sleep(backoff);
    }
  }
  throw lastErr || new Error('aiGlossary: unknown failure');
}

async function seedAiGlossary({ force = false } = {}) {
  const genAI = await getGenAI();
  const existing = await db.collection(COLL).get();
  const have = new Map();
  existing.forEach((d) => have.set(d.id, d.data() || {}));

  const todo = GLOSSARY_TERMS.filter((t) => {
    if (force) return true;
    const cur = have.get(t.slug);
    return !cur || !cur.term_he || !cur.definition_he;
  });

  logger.info(`[aiGlossary.seed] ${todo.length} terms to translate (force=${force})`);

  const results = await pMap(todo, async (term) => {
    const { term_he, definition_he } = await translateOne(genAI, term);
    return { term, term_he, definition_he };
  }, 4);

  const batch = db.batch();
  let written = 0;
  const failures = [];
  for (let i = 0; i < results.length; i++) {
    const r = results[i];
    if (!r) continue;
    if (!r.ok) { failures.push({ slug: todo[i].slug, error: String(r.error && r.error.message) }); continue; }
    const { term, term_he, definition_he } = r.value;
    const ref = db.collection(COLL).doc(term.slug);
    batch.set(ref, {
      slug: term.slug,
      term_en: term.term_en,
      term_he,
      definition_en: term.definition_en,
      definition_he,
      category: term.category,
      relatedTools: [],
      aliases: term.aliases || [],
      order: term.order,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    }, { merge: true });
    written++;
  }

  // Also upsert any terms that already had Hebrew but might need EN refresh
  // (slug + term_en + definition_en + order + category + aliases drift).
  for (const term of GLOSSARY_TERMS) {
    if (todo.find((t) => t.slug === term.slug)) continue; // already in batch above
    const ref = db.collection(COLL).doc(term.slug);
    batch.set(ref, {
      slug: term.slug,
      term_en: term.term_en,
      definition_en: term.definition_en,
      category: term.category,
      aliases: term.aliases || [],
      order: term.order,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    }, { merge: true });
  }

  await batch.commit();
  return { written, skipped: GLOSSARY_TERMS.length - todo.length, failures, total: GLOSSARY_TERMS.length };
}

async function getAiGlossary(/* { language = 'en' } = {} */) {
  const snap = await db.collection(COLL).get();
  const items = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
  items.sort((a, b) => {
    const ca = CATEGORY_ORDER[a.category] ?? 99;
    const cb = CATEGORY_ORDER[b.category] ?? 99;
    if (ca !== cb) return ca - cb;
    return (a.order || 0) - (b.order || 0);
  });
  return { items };
}

async function getAiGlossaryTerm(slug) {
  if (!slug || typeof slug !== 'string') throw new Error('slug required');
  const doc = await db.collection(COLL).doc(slug).get();
  if (!doc.exists) return null;
  const data = { id: doc.id, ...doc.data() };
  // Lookup related tools (max 6)
  const relatedTools = [];
  if (Array.isArray(data.relatedTools) && data.relatedTools.length) {
    const slugs = data.relatedTools.slice(0, 6);
    const fetches = await Promise.all(slugs.map((s) =>
      db.collection('ai_tools').doc(s).get().catch(() => null),
    ));
    for (const d of fetches) {
      if (d && d.exists) {
        const t = d.data();
        relatedTools.push({ slug: d.id, name: t.name, type: t.type, iconUrl: t.iconUrl || null });
      }
    }
  }
  return { ...data, relatedToolsFull: relatedTools };
}

module.exports = {
  GLOSSARY_TERMS,
  CATEGORY_ORDER,
  seedAiGlossary,
  getAiGlossary,
  getAiGlossaryTerm,
};
